title: CellScopes_Test
description: >- 
  This repo notes the test documents for CellScopes at https://github.com/HaojiaWu/CellScopes.jl.
baseurl: "CellScopes_test" # the subpath of your site, e.g., /repository
url: "https://builderpie.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima 
plugins:
  - jekyll-feed
